services:
  - type: web
    name: nexretriever-rag-chatbot
    env: python
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
